# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
  - package-ecosystem: "cargo"
    directories: ["/", "/integration", "/test-runner"]
    schedule:
      interval: "daily"
    groups:
       cargo-deps:
          patterns:
            - "*"
    # we could be stricter for /integration and /test-runner, but the main point is
    # that dependabot should recognize this as a library!
    versioning-strategy: "increase-if-necessary"
