[package]
name = "wasm_split_cli_support"
version = "0.1.0"
edition = "2021"

[dependencies]
eyre = { version = "0.6.12" }
tracing = { version = "0.1", default-features = false, features = ["std"] }
clap = { version = "4.5.4", features = ["derive"], optional = true }
lazy_static = "1.4.0"
regex = "1.10.4"
wasm-encoder = { version = "0.206.0", features = ["wasmparser"] }
wasmparser = "0.206.0"

[lib]
name = "wasm_split_cli_support"

[[bin]]
name = "wasm_split_cli"
required-features = ["build-binary"]

[features]
build-binary = ["dep:clap"]
