[package]
name = "undefined_data"
version.workspace = true
edition.workspace = true
publish.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm_split_helpers.workspace = true

[dev-dependencies]
wasm-bindgen-test.workspace = true

[build-dependencies]
autocfg.workspace = true
rustversion.workspace = true
