[workspace]
# this is in its own workspace to disconnect the toolchain requirement

[package]
name = "wasm-split-test-runner"
version = "0.2.105"
authors = []
edition = "2024"
publish = false
default-run = "wasm-split-test-runner"

[dependencies]
# this MUST be the same bindgen version as used on the tested artifact
wasm-bindgen-cli = { version = "=0.2.128", artifact = ["bin:wasm-bindgen-test-runner", "bin:wasm-bindgen"] }
wasm_split_cli_support = { path = "../crates/wasm_split_cli" }
eyre = "0.6.12"
tempfile = "3.27.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3.23", features = ["fmt", "env-filter"] }
tracing-chrome = "0.7.2"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.150"
serde_with = "3.21.0"
sha2 = "0.11.0"
exec = "0.3"

[[bin]]
name = "wasm-bindgen-cli-wrapper"

[[bin]]
name = "wasm-split-test-runner"
