name: main tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  integration-tests:
    runs-on: macos-latest
    strategy:
      matrix:
        toolchain: ["1.84", stable, nightly]
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
          targets: wasm32-unknown-unknown
      - uses: cargo-bins/cargo-binstall@v1.15.9
      - run: cargo binstall just
      - uses: browser-actions/setup-chrome@v2
        id: setup-chrome
        with:
          install-chromedriver: true

      - name: Run integration tests
        run: just test-integrations
