[package]
name = "wasm_split_helpers"
version = "0.2.0-rc.0"
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
async-once-cell = "0.5.3"
wasm_split_macros.workspace = true
